### ISSUE TITLE
strictTemplates warns about ngxClipboard

### ISSUE THREAD

**Issue by mircowidmer** [maxisam/ngx-clipboard#239]
When I enable `"strictTemplates": true` in my angular compiler options, it warns me about the second line:

```
    <button ngxClipboard
            [cbContent]="'any content'"></button>
```

`error TS2322: Type 'undefined' is not assignable to type 'HTMLInputElement | HTMLTextAreaElement'.`

I'm using Angular 9 and ngxClipboard 13.

**Comment by maxisam** [comment]
have you tried skipLibCheck = true?

**Comment by maxisam** [comment]
https://github.com/maxisam/ngx-clipboard/blob/3b1cb50a8ae6108bfa94e16174679a5279926825/projects/ngx-clipboard/src/lib/ngx-clipboard.directive.ts#L12

I think it is caused by this line.

probably should be `public targetElm: HTMLInputElement | HTMLTextAreaElement | undefined`

**Comment by maxisam** [comment]
could you test 13.0.1-beta01?

**Comment by mircowidmer** [comment]
Unfortunately I can't reproduce the issue either with 13.0.0 or 13.0.1-beta01 in a vanilla angular application project.

I'm using

```
"angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictTemplates": true,
    "strictInjectionParameters": true
  },
```
and 
```
    "strict": true,
    "skipLibCheck": true
```

and can't reproduce the problem with either 13.0.0 or 13.01.-beta01. Somehow the two projects differ in another area as well :/

**Comment by maxisam** [comment]
ah... that is odd. Well, did you test 13.0.1-beta01 in your original proj

**Comment by mircowidmer** [comment]
Yes.

**Comment by maxisam** [comment]
And does it work?

**Comment by mircowidmer** [comment]
In my original project, the error TS2322 still occurs. I ended up using a simple custom-made directive for now. Thanks for the support!

**Comment by maxisam** [comment]
That's odd. I don't have better idea now.

**Comment by mircowidmer** [comment]
That's perfectly ok. I hope your fix still benefits the project. You can close the issue if you'd like. Maybe I'll get around to check it out more detailed in the future.

**Comment by maxisam** [comment]
I will leave it open for a while to see if anyone experience the same thing. 

If you somehow can reproduce in a simple testing project. Maybe I can fix it.

**Comment by maxisam** [comment]
Also, make sure your typescript version is the latest support version. I think this issue might be related to typescript

**Comment by mircowidmer** [comment]
Ok, I was able to reproduce the problem with a very minimal example project, see https://github.com/mircowidmer/ngx-clipboard

**Comment by maxisam** [comment]
ok I think the problem is strictTemplates mode. This is only for Ivy but the library is not built in Ivy for now according to Angular team's suggestion. I will continue to monitor this issue. But currently I don't know how to fix it.

**Comment by kmaraz** [comment]
Hi, it happened to me also. 

This is the UGLY HACK I have used: 

`[ngxClipboard]="$any('')"`

It works, but is very ugly.

**Comment by DmitryEfimenko** [comment]
+1 to this. The issue indeed has to do with the combination of enabling strict template checks and the type of the element the directive `ngxClipboard` is used on. Currently it's only allowing to be used on `HTMLInputElement | HTMLTextAreaElement`:
```
public targetElm: HTMLInputElement | HTMLTextAreaElement;
```
This will fail when using this directive on any other elements (the version 13.0.1-beta01 fails too). For example, I have a use-case:
```
<div ngxClipboard cbContent="something to copy"></div>
```
So clicking on a div should copy the provided content. However, this won't compile.
To fix this, the `targetElm` should simply allow any `HTMLElement`
```
public targetElm: HTMLElement;
```
Although I'm wondering if this is still too restrictive. What if somebody wants to use this directive on an Angular component? As far as I know these are not of type `HTMLElement`. Also not sure about the use-case of using the directive on a web component (custom element).

Perhaps giving it type `any` is a safest way to go:
```
public targetElm: any;
```

**Comment by Maximaximum** [comment]
I'm also experiencing the same issue.

However, strictly speaking, it has nothing to do with the `fullTemplateTypeCheck` settings. It's just that having `fullTemplateTypeCheck` enabled brings this issue to light and lets compiler emit an error, whereas without `fullTemplateTypeCheck` the issue simply gets ignored by the Angular compiler.

Anyway, the real underlying issue is that `ngx-clipboard` is compiled without using the typescript's `strictNullChecks` option. Using this option is often considered to be a best practice for creating Angular libraries. IMHO, however, it's an absolute **MUST** for ANY public Angular library to use it. Unfortunately, having `strictNullChecks` disabled in the library project produces `*.d.ts` typing files which are completely unusable by applications that DO have `strictNullChecks` enabled.

So, the easiest way to fix this issue would be to turn the `strictNullChecks` option on in the `tsconfig.json` file of the `ngx-clipboard` project, and then update all the type annotations within `ngx-clipboard` to properly deal with `undefined` and `null` types.

Please let me know if any additional explanation/help needed, @maxisam. I really hope that this issue will get fixed soon.

**Comment by maxisam** [comment]
@Maximaximum  Thanks! Please test v13.0.1-beta02.

**Comment by Maximaximum** [comment]
Hi @maxisam! 

I've tried the beta, and I have to admit that, besides `strictNullChecks` there's actually an additional issue with `strictTemplates`. Seems like now your code is working fine with the `undefined` values, but it actually needs to support the `''` value, because that's what `<div ngxClipboard></div>` actually resolves to.

So, now there are 2 options:
* Update the type of `targetElm` to `HTMLInputElement | HTMLTextAreaElement | ''` (or even `HTMLInputElement | HTMLTextAreaElement | undefined | ''`) instead of `HTMLInputElement | HTMLTextAreaElement | undefined`;
* Add a static property on the `ClipboardDirective`: `static ngAcceptInputType_targetElm: 
HTMLInputElement | HTMLTextAreaElement | '';`.

Personally, I'd rather go with the 2nd option, since IMHO it's a bit more clear and readable.

**Comment by Maximaximum** [comment]
Please also note that in order to test this you can simply create a new Angular 9 project and set these options in tsconfig.json:
```json
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictTemplates": true
  }
```

```javascript
"compilerOptions": {
    // other options
    ...
    "strictNullChecks": true
}
```

**Comment by maxisam** [comment]
@Maximaximum  please try v13.0.1-beta03. It works on mine.

I ended up go with the option1 because I have never seen the usage of option2. Mind if you can share the reference?

**Comment by Maximaximum** [comment]
Ah yes, sorry, I forgot to add the link to the docs: https://angular.io/guide/template-typecheck#input-setter-coercion

**Comment by Maximaximum** [comment]
I've tested v13.0.1-beta03. The `ngxClipboard` (`targetElm`) works fine.

However, the similar technique should be applied to the whole project. 

In particular, I'm getting an error while trying to bind `[cbContent]` to a value of type `string | undefined`. I guess that people might experience the same issue with other inputs as well.

I'd suggest you to read about strictNullChecks and update the project's codebase in conformance to this concept: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#--strictnullchecks

**Comment by maxisam** [comment]
Please try v13.0.1-beta04 

I forgot cbContent could be undefined.

**Comment by Maximaximum** [comment]
It seems to work just fine now, thank you.

Waiting for the official release!

**Comment by maxisam** [comment]
Thank you for your help! v13.0.1 is out.

**Comment by Maximaximum** [comment]
Thanks, @maxisam!
