### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by davidshen84** [maxisam/ngx-clipboard#245]
Angular 10 requires at least `tslib v2.0.0`.

**Comment by maxisam** [comment]
upgrade to 10 should be pretty easy. Welcome to make  a pull request : )

**Comment by maxisam** [comment]
please try 14.0.0-beta01

**Comment by abdatta** [comment]
Hi @maxisam ! Can you please merge this PR soon and publish it on npm? I have tried out 14.0.0-beta01 and it seems to work perfectly fine for me. Thanks for this helpful package!

**Comment by davidshen84** [comment]
Or you can use the cdk clipboard
https://material.angular.io/cdk/clipboard/api

**Comment by abdatta** [comment]
Thanks for that @davidshen84 ! Didn't realise angular/cdk had its own clipboard support. I guess this library is not needed anymore?

**Comment by maxisam** [comment]
@abdatta I just merged it. I will release it later
It depends on you if you want to use this library. I will keep maintain this because I use it on my own production. If I don't use it anymore, I will let people know.

The reason I didn't merge because I think it is part of community's responsibility to confirm if it works when I release the beta.
