### ISSUE TITLE
TypeError: Clipboard is not a constructor

### ISSUE THREAD

**Issue by d-theo** [maxisam/ngx-clipboard#28]
Hi,
I'm a beginner with Angular and I'm trying to integrate your library. Everything works well in development mode but when I try to browserify my app (or using systemjs-builder) I get this error : 

`TypeError: Clipboard is not a constructor`
with the corresponding line : 
`this.clipboard = new Clipboard(this.elmRef.nativeElement, option);`

after investigating a little bit, I noticed that in order to work, the code should be : 
`this.clipboard = new Clipboard.default(this.elmRef.nativeElement, option);`

but I have no idea how to fix that...
edit: changing the tscconfig.json module from "es2015" to "commonJS" and compiling the project seems to work. The biggest change is that the resulted files use `require('clipboard')`; instead of `import`
Could the import/export mechanism be broken somewhere ?

**Comment by maxisam** [comment]
I believe it is caused by module. This issue is somehow similar with https://github.com/maxisam/ngx-clipboard/issues/22
And I am sorry I haven't have a good way to address it.

However, I think you should try to use webpack and set tsconfig to Es2015 for production. It seems like the best practice currently to work with angular.

I would suggest you start with angular CLI and use eject command to generate webpack config for you.

**Comment by maxisam** [comment]
close for now. I will reopen if there is any more question.
